# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
                ('company_contact_no', models.CharField(max_length=200)),
                ('pic_name', models.CharField(max_length=200)),
                ('consultant', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('point', models.CharField(max_length=200)),
                ('parameter_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('point', models.CharField(max_length=200)),
                ('work_unit', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('flow_rate', models.CharField(max_length=200)),
                ('media', models.CharField(max_length=200)),
                ('technique', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=200)),
                ('classification_value', models.CharField(max_length=200)),
            ],
        ),
    ]
