# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_company_parameter_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='type',
            name='company_name',
        ),
        migrations.AddField(
            model_name='type',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporting.Company'),
            preserve_default=False,
        ),
    ]
