# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20170428_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='pic_name',
            new_name='company_pic',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='type',
            new_name='area_personal_type',
        ),
        migrations.RemoveField(
            model_name='type',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.AddField(
            model_name='company',
            name='company_country',
            field=models.CharField(blank=True, choices=[('MY', 'Malaysia'), ('SG', 'Singapore')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='area_personal_type',
            field=models.CharField(blank=True, choices=[('area', 'Area'), ('personal', 'Personal')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='classification_type',
            field=models.CharField(blank=True, choices=[('twa', 'TWA'), ('mel', 'MEL'), ('cl', 'CL')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
