# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20170428_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='areapersonaltype',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areapersonaltype',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
