# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20170428_2310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('company_name', 'company_country')]),
        ),
    ]
