# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20170429_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='areapersonaltype',
            name='is_active',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='is_active',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
