# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20170505_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='company',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='point',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='area_personal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AreaPersonalType'),
        ),
    ]
