# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20170509_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporting.Company'),
            preserve_default=False,
        ),
    ]
