# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20170509_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='company',
        ),
    ]
